### ISSUE TITLE
Allow updating yaml files with only the recipient public key

### ISSUE THREAD

**Issue by WillAbides** [sylr/yage#30]
I would like to be able to update a secret in a yaml file without having access to the recipient's id file. I may be mistaken, but I don't think this is possible currently.

What I propose is adding a `--update` flag that will work similar to `--rekey` except it does not modify tagged values that are already encrypted.

For example if this is secrets.yaml:

```
$ cat secrets.yaml

foo: !crypto/age |-
  -----BEGIN AGE ENCRYPTED FILE-----
  YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NzZRUVhzTGJzc0dxWk5h
  ejlrUFZRZFdjSmRFK0c2SWk3SlFMcnZYOXl3CkREZTZiRG92TjJZbGxua3Y0Wmw0
  SGsxdk92WWVMbTdJOE5yb28vTHpEcmsKLS0tIFJ3WUJ5R2ZGVjBqcUhmMDA0ZjVa
  ZjA5VlpjQU5kT0theU95YVYyajI2czQKSu4iwDfQnx5ZFHhlQ6yxl13Lgwe3YIKw
  nBcrwHwNMjvKJoU=
  -----END AGE ENCRYPTED FILE-----
bar: something not encrypted
baz: !crypto/age baz

$ yage -r age1fhx57kjhq52pgy8ulczqe8ph4rzyc6gcmn43ygxagwj0x7kaepfq2rpsgm -y --update secrets.yaml

$ cat secrets.yaml

foo: !crypto/age |-
  -----BEGIN AGE ENCRYPTED FILE-----
  YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NzZRUVhzTGJzc0dxWk5h
  ejlrUFZRZFdjSmRFK0c2SWk3SlFMcnZYOXl3CkREZTZiRG92TjJZbGxua3Y0Wmw0
  SGsxdk92WWVMbTdJOE5yb28vTHpEcmsKLS0tIFJ3WUJ5R2ZGVjBqcUhmMDA0ZjVa
  ZjA5VlpjQU5kT0theU95YVYyajI2czQKSu4iwDfQnx5ZFHhlQ6yxl13Lgwe3YIKw
  nBcrwHwNMjvKJoU=
  -----END AGE ENCRYPTED FILE-----
bar: something not encrypted
baz: !crypto/age |-
  -----BEGIN AGE ENCRYPTED FILE-----
  YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ3pLNXhwb2taWjlUZU1m
  cWdVV0FjekJpQksrTEI0UEJTTkxmSFM1WkU4CjZUWFIwb0dUWHp0d1BzdGpGN1M2
  bmxHd05GZmMxVWVKWElCdW5TS0U0M0UKLS0tIG53cDlaS2RqOGtzekVkeFVHWHpp
  dWFjVWsyUHQ5bDVXKzB4REorQmFtQWMKGQ1gpxsQOc8Ks5AXIN+54UV68X85p6/G
  6u5LFHOJ0lv1UrI=
  -----END AGE ENCRYPTED FILE-----
```

My use case for this is to create a system where developers can set up a new app with a continuous deployment system that uses yage for secret management without having to manually transmit the private key. When a new app is added the cd system will create an age key pair for its secrets and emit the public key for developers to use with yage.

This also has the benefit of reducing the number of copies of the private key thus reducing the risk of compromised secrets.

One possible objection to `--update` is that careless use could cause a single yaml file to have fields encrypted with different recipients lists. This would fail at deploy time, so it would mainly be an annoyance, but it would still be a big annoyance when it happens. From my reading of the age spec, I don't think it is possible to determine whether an existing encrypted file has a given recipient without the recipient's private key. That limits our ability to mitigate this issue in the yage command, but there are a few other options available:

1. Add a `.yage-recipients.txt` to the repository to make it convenient for users to use the correct recipients list. To make it easier you could `alias yage=yage -R /path/to/.yage-recipients.txt`
2. If you have a ci system that you trust with your private key, you can add a ci job that makes sure all yage encrypted files can be decrypted.

Let me know what you think. If you like this, I would love to code it up.

**Comment by sylr** [comment]
Hi, glad to see this tool is of use to someone else!

I think your use case makes sense and if you take the time to try to implement it I will be happy to review it.

Cheers.
